config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :pals, controllers: {
      registrations: 'pals/registrations'
  }

  get 'pal/:id' => 'pals#index'
  get 'pal/:id/poster' => 'pals#poster'

  get 'admin'  => 'admin#index'
  get 'admin/pal/:id'  => 'admin#edit_pal', as: 'admin_pal'
  put 'admin/pal/:id'  => 'admin#update_pal'

  get '/:pal_name' => 'pals#index'

end

app/models/pal.rb
class Pal < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, uniqueness: true

  mount_uploader :avatar, AvatarUploader

  def encoded_url
    "http://valpal.rocks/pal/#{id}"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :authenticate_pal!
  before_filter :only_admin!

  def index
    @pals = Pal.all

  end

  def edit_pal
    @pal = Pal.find(params[:id])
  end

  def update_pal
    @person = Pal.find(params[:id])
    @person.update(pal_params)

    @person.avatar = params[:avatar] # Assign a file like this, or
    # u.avatar = File.open('somewhere') # like this
    @person.save!
    # u.avatar.url # => '/url/to/file.png'
    # u.avatar.current_path # => 'path/to/file.png'
    # u.avatar.identifier # => 'file.png'

    redirect_to :action => 'edit_pal'
  end


  private

  def pal_params
    params.require(:pal).permit(:email, :name, :avatar, :longitude, :latitude)
  end

  def only_admin!
    unless current_pal.admin?
      render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @pals = Pal.where("latitude is NOT NULL and longitude is NOT NULL").all
  end

  private

  helper do
    def pal_data(pal)
      {name: pal.name, lat: pal.latitude, long: pal.longitude, url: pal.avatar.url }
    end
  end

end

app/controllers/pals/confirmations_controller.rb
class Pals::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/pals/omniauth_callbacks_controller.rb
class Pals::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/pals/passwords_controller.rb
class Pals::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/pals/registrations_controller.rb
class Pals::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << [:name]
  end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/pals/sessions_controller.rb
class Pals::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/pals/unlocks_controller.rb
class Pals::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/pals_controller.rb
class PalsController < ApplicationController

  def index
    @paypal_endpoint = params[:sandbox].present? ? "www.sandbox.paypal.com" : "www.paypal.com"
    if params[:id]
      @pal = Pal.find(params[:id])
    else
      if params[:pal_name]
        @pal = Pal.where(name: params[:pal_name]).first
      end

      @pal = Pal.new unless @pal
    end

  end

  def poster
    @pal = Pal.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/edit_pal.html.haml
.container
  = link_to 'home', '/'

  %h1 Admin panel

  %p
    id:
    = @pal.id
  %p
    name:
    = @pal.name
  %p
    email:
    = @pal.email

  %p
    %button#locateme
      Locate
  = form_for(@pal, as: @pal, url: admin_pal_path(@pal), html: { method: :put }) do |f|
    .field
      = f.label :email
      %br/
      = f.email_field :email, autofocus: true
    .field
      = f.label :name
      %br/
      = f.text_field :name
    .field
      = f.label :latitude
      %br/
      = f.text_field :latitude
    .field
      = f.label :longitude
      %br/
      = f.text_field :longitude
    .field
      = f.label :avatar

      - if f.object.avatar.url
        %img{src: f.object.avatar.url}
      - else
      = f.file_field :avatar
    .actions
      = f.submit "Update"

    - content_for :javascript do
      :javascript

        $(function(){
          $('#locateme').click(function() {
            if (navigator.geolocation) {
              navigator.geolocation.getCurrentPosition( function(position) {
                $('#pal_latitude').val(position.coords.latitude);
                $('#pal_longitude').val(position.coords.longitude);

              }

            );
          }});

        });

app/views/admin/index.html.haml
.container
  = link_to 'home', '/'
  %h1 Admin
  %table.table.table-striped.table-responsive
    %thead
      %tr
        %th ID
        %th Name
        %th email
        %th avatar
    %tbody
      - @pals.each do |pal|
        %tr
          %td
            %a{:href => "/admin/pal/#{pal.id}"}
              = pal.id
          %td
            = pal.name
          %td
            = pal.email
          %td
            - if pal.avatar.url
              %img{src: pal.avatar.url, height: 50}

app/views/home/index.html.haml
.navbar-wrapper
  .container
    %nav.navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} Val Pal
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            -#%li
            -#  %a{:href => "#about"} About
            -#%li
            -#  %a{:href => "#contact"} Contact
            -#%li.dropdown
            -#  %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            -#    Dropdown
            -#    %span.caret
            -#  %ul.dropdown-menu{:role => "menu"}
            -#    %li
            -#      %a{:href => "#"} Action
            -#    %li
            -#      %a{:href => "#"} Another action
            -#    %li
            -#      %a{:href => "#"} Something else here
            %li.divider
            - unless pal_signed_in?
              %li
                %a{:href => "/pals/sign_in"} Sign in
            - if pal_signed_in?
              - if current_pal.admin
                %li
                  = link_to "admin", '/admin'
              %li
                = link_to "Sign out (#{current_pal.name})", destroy_pal_session_path, :method => :delete
            -#    %li.dropdown-header Nav header
            -#    %li
            -#      %a{:href => "#"} Separated link
            -#    %li
            -#      %a{:href => "#"} One more separated link
/
  Carousel
  \==================================================
#myCarousel.carousel.slide{"data-ride" => "carousel"}
  / Indicators
  %ol.carousel-indicators
    -#%li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
    -#%li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
    -#%li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
  .carousel-inner{:role => "listbox"}
    .item.active
      %img{:alt => "First slide", :src => "https://valpal.s3-ap-southeast-2.amazonaws.com/live_busker_25.jpg"}/
      .container
        .carousel-caption
          %h1.shadowed Val Pal . Rocks

          %p.shadowed
            Buskers and street performs are struggling as our society goes cashless. Val Pal aims to return Value to buskers who provide you Value.
          %p
            - unless pal_signed_in?
              %a.btn.btn-lg.btn-primary{:href => "/pals/sign_up", :role => "button"} Sign up today
            - if pal_signed_in?
              %a.btn.btn-lg.btn-primary{:href => "/#{current_pal.name}", :role => "button"} Your account
            %a.btn.btn-lg.btn-primary{:href => "/amber", :role => "button"} Donate a street performer

    -#.item
    -#  %img{:alt => "Second slide", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="}/
    -#  .container
    -#    .carousel-caption
    -#      %h1 Another example headline.
    -#      %p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
    -#      %p
    -#        %a.btn.btn-lg.btn-primary{:href => "#", :role => "button"} Learn more
    -#.item
    -#  %img{:alt => "Third slide", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAFVVVQAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="}/
    -#  .container
    -#    .carousel-caption
    -#      %h1 One more for good measure.
    -#      %p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
    -#      %p
    -#        %a.btn.btn-lg.btn-primary{:href => "#", :role => "button"} Browse gallery
  -#%a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
  -#  %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
  -#  %span.sr-only Previous
  -#%a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel", :role => "button"}
  -#  %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
  -#  %span.sr-only Next
/ /.carousel
/
  Marketing messaging and featurettes
  \==================================================
/ Wrap the rest of the page in another container to center all the content.
.container.marketing
  / Three columns of text below the carousel
  .row
    .col-lg-4
      %h2 How it works
      %iframe{:allowfullscreen => "", :frameborder => "0", :height => "225", :src => "https://www.youtube.com/embed/zcQLsq5Vx68?rel=0", :width => "400"}
      %p It's simple. Don't have any cash on you? Street performer made you smile? Give value for value.
      %p
        %a.btn.btn-default{:href => "/dawnroh", :role => "button"} See Dawnroh »
    / /.col-lg-4
    .col-lg-4
      %h2 You a street performer?
      %p
        Create an account and start receiving payments via PayPal. All we need to get started is an email address.
      %p
        - unless pal_signed_in?
          %a.btn.btn-default{:href => "/pals/sign_up", :role => "button"} Sign up »
        - if pal_signed_in?
          %a.btn.btn-default{:href => "/#{current_pal.name}", :role => "button"} Your account
    / /.col-lg-4
    .col-lg-4
      %h2 Enjoyed a show?
      %p Find a pal that gave you value and give something back.
      %p
        %a.btn.btn-default{:href => "#explore", :role => "button"} Find pal »
  / /.col-lg-4
  / /.row
  / START THE FEATURETTES
  .row.featurette
    .col-md-12
      %h2.featurette-heading
        %a.a-unstyled{name: "explore"}
          Explore pals
      %p
        - @pals.each do |pal|
          .pal.hidden{data: pal_data(pal) }
        #map-canvas

  -#.row.featurette
  -#  .col-md-5
  -#    %img.featurette-image.img-responsive{:alt => "Generic placeholder image", "data-src" => "holder.js/500x500/auto"}/
  -#  .col-md-7
  -#    %h2.featurette-heading
  -#      Oh yeah, it's that good.
  -#      %span.text-muted See for yourself.
  -#    %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
  -#%hr.featurette-divider/
  -#.row.featurette
  -#  .col-md-7
  -#    %h2.featurette-heading
  -#      And lastly, this one.
  -#      %span.text-muted Checkmate.
  -#    %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
  -#  .col-md-5
  -#    %img.featurette-image.img-responsive{:alt => "Generic placeholder image", "data-src" => "holder.js/500x500/auto"}/
  -#%hr.featurette-divider/
  / /END THE FEATURETTES
  / FOOTER
  %footer
    %p
      \© 2015 Val Pal
      %a{:href => "https://twitter.com/valpaldotrocks"} Twitter
      \·
      %a{:href => "https://www.facebook.com/valpaldotrocks"} Facebook


- content_for :javascript do
  :javascript

    $(function(){

       function initialize() {
        var mapOptions = {
          center: { lat: -37.8148912, lng: 144.966761},
          zoom: 17,
          scrollwheel: false,
          navigationControl: false,
          scaleControl: false,
          draggable: false,
          styles: [
        {
          "featureType": "poi",
          "elementType": "labels",
          "stylers": [
            { "visibility": "off" }
          ]
        }
      ]

        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);

        var pals = $('.pal');
        pals.each(function(i) {
          var p = $(pals[i]);
          console.log(p.data('name'))
          var myLatlng = new google.maps.LatLng(p.data('lat'),p.data('long'));

        var contentString = '<div id="content">'+
        '<img height="50" src="'+p.data('url')+'">'+
        '<h1 id="firstHeading" class="firstHeading">'+p.data('name')+'</h1>'+
        '<div id="bodyContent">'+
        '<p><a href="/'+p.data('name')+'">'+
        'View profile</a> '+
        '</div>'+
        '</div>';

        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });

        var marker = new google.maps.Marker({
              position: myLatlng,
              map: map,
              title: p.data('name')
          });


        google.maps.event.addListener(marker, 'click', function() {
          infowindow.open(map,marker);
        });
        });



      }
       google.maps.event.addDomListener(window, 'load', initialize);
    });

app/views/pals/_pay_form.html.haml
%form{:action => "https://#{@paypal_endpoint}/cgi-bin/webscr", :method => "post", :target => "_top"}
  %input{:name => "cmd", :type => "hidden", :value => "_xclick"}/
  %input{:name => "business", :type => "hidden",  "value"=> (@pal.email.present? ? @pal.email : "{{pal_email}}" ) }/
  %input{:name => "lc", :type => "hidden", :value => "AU"}/
  %input{:name => "item_name", :type => "hidden", :value => value_text }/
  %input{:name => "amount", :type => "hidden", :value => amount}/
  %input{:name => "currency_code", :type => "hidden", :value => "AUD"}/
  %input{:name => "button_subtype", :type => "hidden", :value => "services"}/
  %input{:name => "no_note", :type => "hidden", :value => "0"}/
  %input{:name => "shipping", :type => "hidden", :value => "0.00"}/
  %input{:name => "bn", :type => "hidden", :value => "PP-BuyNowBF:btn_buynowCC_LG.gif:NonHostedGuest"}/
  %input.button.btn.btn-primary.btn-lg.btn-block.btn-value.btn-text{:alt => "PayPal — The safer, easier way to pay online.", :border => "0", :name => "submit", :type=>"Submit", :value=> value_text }

  %img{:alt => "", :border => "0", :height => "1", :src => "https://www.paypalobjects.com/en_AU/i/scr/pixel.gif", :width => "1"}/

app/views/pals/index.html.haml
.container{"ng-app" => ""}
  .header
    %img{src: @pal.avatar.url, height: '180', class: 'pal-image'}
    %h1
      %b.name
        = @pal.name

        - if pal_signed_in?
          - if current_pal == @pal
            %a.btn.btn-lg.btn-primary{:href => "/pal/#{current_pal.id}/poster", :role => "button"} Print poster

  .form-group{:class => ("hidden" if @pal.email.present?)}
    %label
      Busker email {{pal_email}}
    %input.form-control{"type" => "text", "ng-model" => "pal_email", "placeholder" => "email@example.org"}
  .row{"ng-cloak" => ""}
    .col-xs-12.col-md-6
      .row
        .col-xs-6
          = render partial: "pay_form", locals: { value_text: 'smile', amount: '2.00' }
        .col-xs-6
          = render partial: "pay_form", locals: { value_text: 'lol', amount: '5.00' }
      .row
        .col-xs-6
          = render partial: "pay_form", locals: { value_text: 'photo', amount: '10.00' }
        .col-xs-6
          = render partial: "pay_form", locals: { value_text: 'think', amount: '25.00' }
    .col-xs-12.col-md-6
      %i.blurb-text
        %p
          Buskers and street performs are struggling as our society goes cashless.
          Val Pal aims to return Value to buskers who provide you Value.
          With Val Pal you can quickly pay a busker who makes you smile ($2),
          makes you laugh ($5), etc. with any web browsing device.
        %p
          You can even track down a busker you saw earlier and only l
          after that evening or that week you feel that their performance
          was worth giving back some value for.
  %footer
    %p
      \© 2015 Val Pal
      %a{:href => "https://twitter.com/valpaldotrocks"} Twitter
      \·
      %a{:href => "https://www.facebook.com/valpaldotrocks"} Facebook

app/views/pals/poster.html.haml
.container.poster
  %p.poster-text
    Value my performance?
  %p.poster-text
    Did I make you
  .row
    .col-xs-6
      .row
        .col-xs-6
          %button.btn.btn-lg.btn-block.btn-value.btn-text
            SMILE
        .col-xs-6
          %button.btn.btn-lg.btn-block.btn-value.btn-text
            LOL
      .row
        .col-xs-6
          %button.btn.btn-lg.btn-block.btn-value.btn-text
            PHOTO
        .col-xs-6
          %button.btn.btn-lg.btn-block.btn-value.btn-text
            THINK
    .col-xs-6
      %img{src: "https://chart.googleapis.com/chart?chs=400x400&cht=qr&chl=#{@pal.encoded_url}"}
  %p.poster-text
    give me some value back!
  %p
    .poster-text.url-text.highlight.clearfix
      .url
        http://valpal.rocks/
      .empty-box &nbsp;

  %p &nbsp;
  %p &nbsp;
  %p &nbsp;
  %p.poster-text
    %img{src: "/valpal_logo.jpg", alt: "ValPal logo", height: "120"}
  %p.poster-text
    %i
      immediate
      %img{src: "https://www.paypalobjects.com/webstatic/i/logo/rebrand/ppcom.svg", alt: "PayPal logo", height: "60"}
      payments to street performers.